import type { Department } from "./types";

export const initialDepartments: Department[] = [
    {
        id: 1,
        parentId: null,
        name: "본사",
        orderNo: 1,
        managerName: "김민수",
        phone: "02-1000-1000",
        status: "ACTIVE",
        createdAt: "2026-01-18 10:58:15",
        children: [
            {
                id: 2,
                parentId: 1,
                name: "개발본부",
                orderNo: 1,
                managerName: "박준호",
                phone: "02-1000-1100",
                status: "ACTIVE",
                createdAt: "2026-01-18 11:02:10",
                children: [
                    {
                        id: 3,
                        parentId: 2,
                        name: "프론트엔드팀",
                        orderNo: 1,
                        managerName: "최서연",
                        phone: "02-1000-1110",
                        status: "ACTIVE",
                        createdAt: "2026-01-18 11:05:24",
                    },
                    {
                        id: 4,
                        parentId: 2,
                        name: "백엔드팀",
                        orderNo: 2,
                        managerName: "정도윤",
                        phone: "02-1000-1120",
                        status: "ACTIVE",
                        createdAt: "2026-01-18 11:07:31",
                    },
                ],
            },
            {
                id: 5,
                parentId: 1,
                name: "경영지원본부",
                orderNo: 2,
                managerName: "이지은",
                phone: "02-1000-1200",
                status: "ACTIVE",
                createdAt: "2026-01-18 11:10:09",
                children: [
                    {
                        id: 6,
                        parentId: 5,
                        name: "인사팀",
                        orderNo: 1,
                        managerName: "이지은",
                        phone: "02-1000-1210",
                        status: "ACTIVE",
                        createdAt: "2026-01-18 11:12:44",
                    },
                    {
                        id: 7,
                        parentId: 5,
                        name: "재무팀",
                        orderNo: 2,
                        managerName: "김민수",
                        phone: "02-1000-1220",
                        status: "DISABLED",
                        createdAt: "2026-01-18 11:14:02",
                    },
                ],
            },
        ],
    },
];
